/**
 * useImageMap.ts
 *
 * Central image registry for SikPix car art products and gallery.
 *
 * NOTE: All .jpg files here are generated by `generate-images.mjs`.
 * Run that script once before building:
 *   GEMINI_API_KEY=your_key node generate-images.mjs
 */

// ─────────────────────────────────────────────────────────────────────────────
// PRODUCT IMAGES  (1:1 square, used in product cards and product pages)
// ─────────────────────────────────────────────────────────────────────────────
import productGTAStreet      from "@/assets/product-gta-street.jpg";
import productNeonNight      from "@/assets/product-neon-night.jpg";
import productStreetRacerV1  from "@/assets/product-street-racer-v1.jpg";
import productStreetRacerV2  from "@/assets/product-street-racer-v2.jpg";
import productCartoon        from "@/assets/product-cartoon.jpg";
import productLowriderV1     from "@/assets/product-lowrider-v1.jpg";
import productLowriderV2     from "@/assets/product-lowrider-v2.jpg";
import productDriftStyle     from "@/assets/product-drift-style.jpg";

// ─────────────────────────────────────────────────────────────────────────────
// GALLERY IMAGES  (16:9 landscape, used in gallery grid and preview)
// ─────────────────────────────────────────────────────────────────────────────

// GTA Street
import galleryGTASunset      from "@/assets/gallery/gta-sunset.jpg";
import galleryGTANight       from "@/assets/gallery/gta-night.jpg";
import galleryGTADesert      from "@/assets/gallery/gta-desert.jpg";
import galleryGTAHeist       from "@/assets/gallery/gta-heist.jpg";
import galleryGTAPolice      from "@/assets/gallery/gta-police.jpg";

// Neon Night
import galleryNeonTokyo      from "@/assets/gallery/neon-tokyo.jpg";
import galleryNeonRain       from "@/assets/gallery/neon-rain.jpg";
import galleryNeonPurple     from "@/assets/gallery/neon-purple.jpg";
import galleryNeonAlley      from "@/assets/gallery/neon-alley.jpg";
import galleryNeonUnderground from "@/assets/gallery/neon-underground.jpg";

// Street Racer
import galleryRacerHighway   from "@/assets/gallery/racer-highway.jpg";
import galleryRacerTunnel    from "@/assets/gallery/racer-tunnel.jpg";
import galleryRacerPursuit   from "@/assets/gallery/racer-dark-pursuit.jpg";
import galleryRacerApex      from "@/assets/gallery/racer-apex.jpg";
import galleryRacerLaunch    from "@/assets/gallery/racer-launch.jpg";

// Street Racer Dark
import galleryRacer2Underground from "@/assets/gallery/racer2-underground.jpg";
import galleryRacer2Warehouse   from "@/assets/gallery/racer2-warehouse.jpg";
import galleryRacer2Industrial  from "@/assets/gallery/racer2-industrial.jpg";
import galleryRacer2Ramp        from "@/assets/gallery/racer2-ramp.jpg";
import galleryRacer2Rooftop     from "@/assets/gallery/racer2-rooftop.jpg";

// Cartoon
import galleryCartoonFiesta  from "@/assets/gallery/cartoon-fiesta.jpg";
import galleryCartoonCorsa   from "@/assets/gallery/cartoon-corsa.jpg";
import galleryCartoonGolf    from "@/assets/gallery/cartoon-golf.jpg";
import galleryCartoonCivic   from "@/assets/gallery/cartoon-civic.jpg";
import galleryCartoonM4      from "@/assets/gallery/cartoon-m4.jpg";

// Lowrider
import galleryLowriderSunset    from "@/assets/gallery/lowrider-sunset.jpg";
import galleryLowriderPalmBeach from "@/assets/gallery/lowrider-palmbeach.jpg";
import galleryLowriderClassic   from "@/assets/gallery/lowrider-classic.jpg";
import galleryLowriderAvenue    from "@/assets/gallery/lowrider-avenue.jpg";
import galleryLowriderCoastroad from "@/assets/gallery/lowrider-coastroad.jpg";

// Lowrider Night
import galleryLowrider2NeonStrip    from "@/assets/gallery/lowrider2-neonstrip.jpg";
import galleryLowrider2NightCruise  from "@/assets/gallery/lowrider2-nightcruise.jpg";
import galleryLowrider2Lights       from "@/assets/gallery/lowrider2-lights.jpg";
import galleryLowrider2Corner       from "@/assets/gallery/lowrider2-corner.jpg";
import galleryLowrider2PetrolStation from "@/assets/gallery/lowrider2-petrolstation.jpg";

// Drift Style
import galleryDriftTouge    from "@/assets/gallery/drift-touge.jpg";
import galleryDriftSmoke    from "@/assets/gallery/drift-smoke.jpg";
import galleryDriftSideways from "@/assets/gallery/drift-sideways.jpg";
import galleryDriftRain     from "@/assets/gallery/drift-rain.jpg";
import galleryDriftTandem   from "@/assets/gallery/drift-tandem.jpg";

// ─────────────────────────────────────────────────────────────────────────────
// PRODUCT IMAGE MAP
// Maps product ID → product preview image (1:1 square)
// ─────────────────────────────────────────────────────────────────────────────
export const imageMap: Record<string, string> = {
  "gta-street":       productGTAStreet,
  "neon-night":       productNeonNight,
  "street-racer-v1":  productStreetRacerV1,
  "street-racer-v2":  productStreetRacerV2,
  "cartoon":          productCartoon,
  "lowrider-v1":      productLowriderV1,
  "lowrider-v2":      productLowriderV2,
  "drift-style":      productDriftStyle,
};

// ─────────────────────────────────────────────────────────────────────────────
// GALLERY IMAGE MAP
// Maps gallery item ID → gallery image (16:9 landscape)
//
// IDs match the gallery item IDs defined in GalleryPage.tsx.
// For product hero images in the gallery, imageMap above is used instead.
// ─────────────────────────────────────────────────────────────────────────────
export const galleryImageMap: Record<string, string> = {
  // GTA Street sub-images
  "gta-street-heist":       galleryGTASunset,
  "gta-street-vice":        galleryGTANight,
  // standalone keys for future use
  "gta-sunset":             galleryGTASunset,
  "gta-night":              galleryGTANight,
  "gta-desert":             galleryGTADesert,
  "gta-heist":              galleryGTAHeist,
  "gta-police":             galleryGTAPolice,

  // Neon Night sub-images
  "neon-night-rain":        galleryNeonRain,
  "neon-night-tunnel":      galleryNeonTokyo,
  // standalone
  "neon-tokyo":             galleryNeonTokyo,
  "neon-rain":              galleryNeonRain,
  "neon-purple":            galleryNeonPurple,
  "neon-alley":             galleryNeonAlley,
  "neon-underground":       galleryNeonUnderground,

  // Street Racer v1 sub-images
  "street-racer-v1-touge":  galleryRacerHighway,
  "street-racer-v1-drag":   galleryRacerTunnel,
  // standalone
  "racer-highway":          galleryRacerHighway,
  "racer-tunnel":           galleryRacerTunnel,
  "racer-dark-pursuit":     galleryRacerPursuit,
  "racer-apex":             galleryRacerApex,
  "racer-launch":           galleryRacerLaunch,

  // Street Racer v2 sub-images
  "street-racer-v2-night":  galleryRacer2Underground,
  "street-racer-v2-rain":   galleryRacer2Warehouse,
  // standalone
  "racer2-underground":     galleryRacer2Underground,
  "racer2-warehouse":       galleryRacer2Warehouse,
  "racer2-industrial":      galleryRacer2Industrial,
  "racer2-ramp":            galleryRacer2Ramp,
  "racer2-rooftop":         galleryRacer2Rooftop,

  // Cartoon sub-images
  "cartoon-chibi":          galleryCartoonFiesta,
  "cartoon-retro":          galleryCartoonCorsa,
  // standalone
  "cartoon-fiesta":         galleryCartoonFiesta,
  "cartoon-corsa":          galleryCartoonCorsa,
  "cartoon-golf":           galleryCartoonGolf,
  "cartoon-civic":          galleryCartoonCivic,
  "cartoon-m4":             galleryCartoonM4,

  // Lowrider v1 sub-images
  "lowrider-v1-show":       galleryLowriderSunset,
  "lowrider-v1-sunset":     galleryLowriderPalmBeach,
  // standalone
  "lowrider-sunset":        galleryLowriderSunset,
  "lowrider-palmbeach":     galleryLowriderPalmBeach,
  "lowrider-classic":       galleryLowriderClassic,
  "lowrider-avenue":        galleryLowriderAvenue,
  "lowrider-coastroad":     galleryLowriderCoastroad,

  // Lowrider v2 sub-images
  "lowrider-v2-hop":        galleryLowrider2NeonStrip,
  "lowrider-v2-mural":      galleryLowrider2NightCruise,
  // standalone
  "lowrider2-neonstrip":    galleryLowrider2NeonStrip,
  "lowrider2-nightcruise":  galleryLowrider2NightCruise,
  "lowrider2-lights":       galleryLowrider2Lights,
  "lowrider2-corner":       galleryLowrider2Corner,
  "lowrider2-petrolstation": galleryLowrider2PetrolStation,

  // Drift Style sub-images
  "drift-style-angle":      galleryDriftSmoke,
  "drift-style-tandem":     galleryDriftSideways,
  // standalone
  "drift-touge":            galleryDriftTouge,
  "drift-smoke":            galleryDriftSmoke,
  "drift-sideways":         galleryDriftSideways,
  "drift-rain":             galleryDriftRain,
  "drift-tandem":           galleryDriftTandem,
};

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/** Returns the product preview image for a given product ID, fallback to GTA Street. */
export const getProductImage = (productId: string): string =>
  imageMap[productId] ?? productGTAStreet;

/** Returns the gallery image for a given gallery item ID, fallback to product image. */
export const getGalleryImage = (galleryId: string): string =>
  galleryImageMap[galleryId] ?? imageMap[galleryId] ?? productGTAStreet;
